apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "keycloak.fullname" . }}-keycloak-realm-import
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
data:
{{ (.Files.Glob "files/*.json").AsConfig | indent 2 }}
