kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: lgc
nodes:
  - role: control-plane
    # use the control plane as "load balancer" for L7 traffic
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      - containerPort: 443
        hostPort: 443
        protocol: TCP
      - containerPort: 9094
        hostPort: 9094
        protocol: TCP
  - role: worker
  - role: worker
  - role: worker
