apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: {{ .Values.kafka.clusterName }}-default
  labels:
    strimzi.io/cluster: {{ .Values.kafka.clusterName }}
    {{- include "dev-glue.labels" . | nindent 4}}
spec:
  replicas: 1
  roles:
    - controller
    - broker
  resources:
    requests:
      memory: 1Gi
      cpu: 1
    limits:
      memory: 1Gi
      cpu: 1
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 20Gi
        deleteClaim: true
