apiVersion: roundtable.lsst.codes/v1beta1
kind: StrimziSchemaRegistry
metadata:
  name: confluent-schema-registry
  labels:
    {{- include "dev-glue.labels" . | nindent 4}}
spec:
  listener: tls
  securityProtocol: SSL
  registryImageTag: "7.6.0"
