apiVersion: v2
name: strimzi-registry-operator
description: A Helm chart for Kubernetes
type: application
version: 2.1.0
appVersion: 2.1.0
dependencies:
  - name: strimzi-registry-operator
    version: 2.1.0
    repository: https://lsst-sqre.github.io/charts/
